
services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: stockmaster3000
      MYSQL_USER: viet
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - my-network

  springboot-app:
    build:
      context: .
    container_name: springboot-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/stockmaster3000
      SPRING_DATASOURCE_USERNAME: viet
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mariadb
    networks:
      - my-network

networks:
  my-network:
    driver: bridge