sonar.projectKey=myproject
sonar.projectName=Stockmaster3000
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.exclusions=**/.idea/**,**/.mvn/**,**/components/**,**/frontend/**,**/resources/**,**/model/**,**/views/**,**/security/**,**/repository/**,**/client/**,**/service/ProductLogService.class/**,**/Stockmaster3000Application.class/**,**/components/**,**/tab/**,**/InsightsTab.java,**/BarChart.java,**/Category.java,**/CategoryRepository.java,**/CategoryService.java,**/CustomUserDetailsService.java,**/DashboardTab.java,**/DoughnutChart.java,**/HeaderComponent.java,**/Inventory.java,**/InventoryCombox.java,**/InventoryRepository.java,**/InventoryService.java,**/LanguageChangeListener.java,**/LineChart.java,**/LoginView.java,**/MainView.java,**/OpenAIClient.java,**/PreMainView.java,**/Product.java,**/ProductLogService.java,**/ProductRepository.java,**/ProductService.java,**/RegistrationView.java,**/Report.java,**/ReportCombox.java,**/ReportRepository.java,**/ReportService.java,**/ReportsTab.java,**/SecurityConfig.java,**/SecurityService.java,**/Stockmaster3000Application.java,**/Supplier.java,**/SupplierRepository.java,**/SupplierService.java,**/User.java,**/UserRepository.java,**/UserService.java


sonar.host.url=http://localhost:9000
sonar.login="Get your own credentials from SonarQube"
